version: '3.7'

services:
  dev_mysite:
    build: .
    image: dev/mysite
    container_name: dev_mysite
    restart: always
    ports:
      - '127.0.0.1:3000:80'
    command: 'npm run start'
    networks:
      - network_reverse_proxy

networks:
  network_reverse_proxy:
    external: true
