version: '3.7'

services:
  dev_mysite:
    build: .
    image: dev/mysite
    container_name: dev_mysite
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    command: 'npm run start'
    networks:
      - reverse_proxy_network

networks:
  reverse_proxy_network:
    external: true
