version: '3.7'

services:
  dev_mysite:
    build: .
    image: dev/mysite
    container_name: nuxt-app
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    command: 'npm run start'
    networks:
      - reverse_proxy_network
    links:
      - dev_reverse-proxy

networks:
  reverse_proxy_network:
