name: Deploy app with docker-compose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Login by SSH, git pull, Deploy by docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ github.repository }}

            echo '${{ toJson(vars) }}' > env.json
            json=$(cat env.json)
            for key in $(echo "$json" | jq -r 'keys[]'); do
              value=$(echo "$json" | jq -r ".$key")
              echo "$key=$value" >> .env
            done

            ls -a
            cat .env

            git pull origin master
            docker-compose down
            docker-compose up -d --build

