name: Deploying $GITHUB_REPOSITORY

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_ROOT: $API_ROOT
      GTM_ID: $GTM_ID

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            repository_name=${basename `git rev-parse --show-toplevel`}
            cd ~/home/${{ secrets.USERNAME }}/$repository_name
            git pull origin master
            docker-compose down
            docker-compose up -d --build
