name: Test variables

on:
  push:
    branches:
      - master

jobs:
  logger-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        env:
          API_ROOT: ${{ vars.API_ROOT }}
          GTM_ID: ${{ vars.GTM_ID }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ github.repository }}
            git pull origin master
            docker-compose down
            docker-compose up -d --build

