name: Deploy app with docker-compose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login by SSH, git pull, Deploy by docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          allenvs: true
          port: 22
          script: |
            echo ${{ toJson(vars) }}
            cd ${{ github.repository }}
            git pull origin master
            docker-compose down
            docker-compose up -d --build

