name: Deploy app with docker-compose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env
        run: |
          url="https://google.com"
          dir="${{ secrets.USERNAME }}"
          echo API_ROOT="$url" >> .env
          echo DIR="$dir" >> .env

      - name: Загрузить файл
        uses: actions/upload-artifact@v2
        with:
          name: .env
          path: .env

      - name: Login by SSH, git pull, Deploy by docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ github.repository }}
            env_contents=$(cat .env)
            echo "$env_contents" > .env
            git checkout master
            git pull
            docker-compose up -d --build

